# Site settings
title: "Bryan Mikaelian - Resume"
description: "Bryan Mikaelian: Backend Engineer with over a decade of experience building platforms and control planes."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Bryan Mikaelian"
resume_title:                   "Staff Backend Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "bryan.mikaelian@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "214-532-7112"
resume_contact_address:         "10010 Prestwich Ter, Ijamsville, MD 21754"

resume_header_contact_info:     "10010 Prestwich Ter, Ijamsville, MD 21754 • 214-532-7112 • bryan.mikaelian@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "
<p>
   Backend engineer with over 15 years of experience specializing in high-scale API development and control plane services. Deep expertise in architecting systems that process streaming data for monitoring and analytics platforms, handling multiple terabytes of data daily. Demonstrated success in transforming billing systems and optimizing usage data pipelines, reducing processing times by up to 96%. Seeking a role with a small, agile team where I can leverage my technical acumen to make immediate impact, with the autonomy to drive decisions and own complex systems end-to-end.
</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bryanmikaelian"
  resume_twitter_url:           "http://twitter.com/bryanmikaelian"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/bryanmikaelian"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://bryanmikaelian.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
